spring:
  cloud: 
    config: 
      override-none: true
  application:
    name: order-service
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
      
feign:
  hystrix:
    enabled: true
 # httpclient:
  #  connection-timeout: 1000
  command: 
        default:
            execution:
              timeout:
                enabled: true
              isolation:
                    thread:
                        timeoutInMilliseconds: 900

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
---
spring:
  profiles: order1
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202
  

